# from clhenrick

# Title of your website
title: "Olivia Weseley - Portfolio"

title_short: "Olivia Weseley"

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Welcome to my code portfolio. Make yourself at home."

# Main author of the website
# See > authors.yml
author: olwesel

plugins: [jekyll-paginate]

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "Olivia Weseley's Coding Portfolio"
description: [A short description of your site's purpose]
